version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/test/files
volumes:
  db:
    driver: local
