apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors
  template:
    metadata:
      labels:
        app: authors
    spec:
      initContainers:
        - name: run-migrations
          image: authors-migrations:0.1
          imagePullPolicy: Never
          command: [
              'migrate',
              '-path',
              '/migrations',
              '-database',
              '$(POSTGRESQL_URL)',
              'goto',
              '$(VERSION)',
            ] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
          env:
            - name: POSTGRESQL_URL
              value: 'postgres://demo:demo@postgres-authors:5432/demo?sslmode=disable'
            - name: VERSION
              value: '20221030101907'
      containers:
        - image: authors:0.1
          imagePullPolicy: Never
          name: authors
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: authors-config
            - secretRef:
                name: authors-secret
