apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-deployment
spec:
  replicas: 1 # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: subscriptions # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: subscriptions # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations-subscriptions
          image: subscriptions-migrations:0.1
          command: [
              'migrate',
              '-path',
              '/migrations',
              '-database',
              '$(POSTGRESQL_URL)',
              'goto',
              '$(VERSION)',
            ] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
          env:
            - name: POSTGRESQL_URL
              value: 'postgres://postgres:postgres@postgres-subscriptions:5432/demo?sslmode=disable'
            - name: VERSION
              value: '20221030231112'

      containers:
        - image: subscriptions:0.1 # образ Docker
          name: subscriptions # ім'я контейнеру
          imagePullPolicy: Never # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          ports:
            - containerPort: 8080 # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: subscriptions-config
            - secretRef:
                name: subscriptions-secret
