image:
  name: playlists
  tag: 0.1

postgresql:
  nameOverride: postgres-playlists
  fullnameOverride: postgres-playlists
  postgresqlDatabase: 'playlists'
  postgresqlUsername: 'playlists'
  postgresqlPassword: 'playlists'
  persistence:
    size: 1Gi
    mountPath: /var/lib/pg/data/playlists

migrations:
  image:
    name: playlists-migrations
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://playlists:playlists@postgres-playlists:5432/playlists?sslmode=disable'
    VERSION: '20230112080808'

configs:
  POSTGRES_DB: playlists
  POSTGRES_HOST: postgres-playlists

secrets:
  POSTGRES_USER: 'cGxheWxpc3Rz'
  POSTGRES_PASSWORD: 'cGxheWxpc3Rz'

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/playlists
  port: http
