image:
  name: users
  tag: 0.1

postgresql:
  nameOverride: postgres-users
  fullnameOverride: postgres-users
  postgresqlDatabase: 'users'
  postgresqlUsername: 'users'
  postgresqlPassword: 'users'
  persistence:
    size: 1Gi
    mountPath: /var/lib/pg/data/users

migrations:
  image:
    name: users-migrations
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://users:users@postgres-users:5432/users?sslmode=disable'
    VERSION: '20221030101907'

configs:
  POSTGRES_DB: users
  POSTGRES_HOST: postgres-users

secrets:
  POSTGRES_USER: ''
  POSTGRES_PASSWORD: ''

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/users
  port: http
