image:
  name: subscriptions
  tag: 0.1

  postgresql:
  fullnameOverride: postgres-subscriptions
  postgresqlDatabase: 'demo'
  postgresqlUsername: 'demo'
  postgresqlPassword: 'demo'
  persistence:
    size: 1Gi
    mountPath: /var/lib/pg/data/subscriptions

migrations:
  image:
    name: subscriptions-migrations
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://demo:demo@postgres-subscriptions:5432/demo?sslmode=disable'
    VERSION: '20221030231112'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres-subscriptions

secrets:
  POSTGRES_USER: 'ZGVtbw=='
  POSTGRES_PASSWORD: 'ZGVtbw=='

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/subscriptions
  port: http
