apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      {{ .Values.selector | toYaml }}                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        {{ .Values.selector | toYaml }}               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: {{ .Values.migrations.image.name }}
          image: {{ .Values.migrations.image.name }}:{{ .Values.migrations.image.tag }}
          imagePullPolicy: Never
          command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)"] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
          env:
            - name: POSTGRESQL_URL
              value: {{ .Values.migrations.config.POSTGRESQL_URL | quote }}
            - name: VERSION
              value: {{ .Values.migrations.config.VERSION | quote }}
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}      # образ Docker
          name: {{ .Values.image.name }}           # ім'я контейнера
          imagePullPolicy: Never
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: TCP
            {{- end }}  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
