apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
spec:
  type: ClusterIP      # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}      # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу
