image:
  name: tracks
  tag: 0.1

postgresql:
  fullnameOverride: postgres-tracks
  postgresqlDatabase: 'demo'
  postgresqlUsername: 'demo'
  postgresqlPassword: 'demo'
  persistence:
    size: 1Gi
    mountPath: /var/lib/pg/data/tracks

migrations:
  image:
    name: tracks-migrations
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://demo:demo@postgres-tracks:5432/demo?sslmode=disable'
    VERSION: '20221029185755'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres-tracks

secrets:
  POSTGRES_USER: 'ZGVtbw=='
  POSTGRES_PASSWORD: 'ZGVtbw=='

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/tracks
  port: http
